export const assessmentData = [
  {
    id: 1,
    title: "Math Assessment",
    date: "20 Apr 2023",
    duration: "00",
    questions: "00",
  },
  // {
  //   id: 2,
  //   title: "Physics Assessment",
  //   date: "25 Apr 2023",
  //   duration: "01",
  //   questions: "10",
  // },
  // {
  //   id: 3,
  //   title: "Chemistry Assessment",
  //   date: "30 Apr 2023",
  //   duration: "01",
  //   questions: "15",
  // },
  // {
  //   id: 4,
  //   title: "Biology Assessment",
  //   date: "5 May 2023",
  //   duration: "00",
  //   questions: "05",
  // },
  // {
  //   id: 5,
  //   title: "History Assessment",
  //   date: "10 May 2023",
  //   duration: "01",
  //   questions: "20",
  // },
  // {
  //   id: 6,
  //   title: "English Assessment",
  //   date: "15 May 2023",
  //   duration: "00",
  //   questions: "25",
  // },
  // {
  //   id: 7,
  //   title: "Geography Assessment",
  //   date: "20 May 2023",
  //   duration: "01",
  //   questions: "18",
  // },
  // {
  //   id: 8,
  //   title: "Computer Science Assessment",
  //   date: "25 May 2023",
  //   duration: "01",
  //   questions: "30",
  // },
  // {
  //   id: 9,
  //   title: "Art Assessment",
  //   date: "30 May 2023",
  //   duration: "00",
  //   questions: "12",
  // },
  // {
  //   id: 10,
  //   title: "Music Assessment",
  //   date: "5 Jun 2023",
  //   duration: "00",
  //   questions: "08",
  // },
];
